### PR TITLE
API can now retreive all lyrics for an artist

### PR DESCRIPTION
**Pull request by Aarkon**
Also, lists of songs and albums can be looked up, and I extracted the code for processing the lyrics to an own method

### CODE REVIEW

**Comment by Aarkon** [comment]
I forgot to mention that I also swept over useless blank lines, still being in O(n). :)

**Comment by res0nance** [comment]
Hey @Aarkon love the work but now its no longer compatible with older versions of python due to line 19

**Comment by Aarkon** [comment]
I finally figured out how to run this with correct encodings under python2.7. \o/
Also, I added some tests. Not sure if we are at 100% coverage again, though. And you may want to check the imports I made in the test file: They look significantly different from yours and I don't know how to imitate yours. ;)

**Comment by res0nance** [comment]
@Aarkon Nice it works ill merge this now

**Pull request merged**
